apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ConversionLabs
  annotations:
    github.com/project-slug: cbdurietz/ConversionLabs
spec:
  type: Labs
  lifecycle: unknown
  owner: guests
